name: Deployment

on: [push]

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      # Authenticate to Google Cloud
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      # Set up Google Cloud SDK
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      # Deploy the Cloud Functions
      - name: Deploy Cloud Functions
        run: |
          for dir in src/*/; do
            function_name=$(basename "$dir")  # 폴더 이름에서 함수 이름 가져오기
            echo "Deploying function: $function_name"
            gcloud functions deploy ${function_name} \
              --region europe-west1 \
              --runtime nodejs20 \
              --source "$dir" \
              --entry-point ${function_name} \
              --trigger-http \
              --allow-unauthenticated \
              --timeout 60 \
              --max-instances 1 \
              --no-gen2
          done
