name: Deployment

on:
  push:
    branches:
      - main  # main 브랜치에 푸시될 때만 작동

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      # Authenticate to Google Cloud
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      # Set up Google Cloud SDK
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      # Get modified files
      - name: Get changed files
        id: filter
        uses: dorny/paths-filter@v2
        with:
          filters: |
            src:
              - 'src/**/*'

      # Deploy the Cloud Functions
      - name: Deploy Cloud Functions
        run: |
          modified_files=()
          modified_dirs=()
          echo "Src filter result: ${{ steps.filter.outputs.src }}"  # src 필터 결과 출력
          echo "Changed files output: ${{ steps.filter.outputs.src_files }}"  # 변경된 파일 리스트 출력

          if [[ "${{ steps.filter.outputs.src }}" == "true" ]]; then
              modified_files=($(echo "${{ steps.filter.outputs.src_files }}" | tr ',' ' '))  # 변경된 파일 리스트를 배열로 변환

              echo "Modified files: ${modified_files[@]}"  # 변경된 파일 출력

              for file in "${modified_files[@]}"; do
                src_dir=$(dirname "$file")  # src 디렉토리 가져오기
                echo "Adding directory: $src_dir" 
                modified_dirs+=("$src_dir")
              done
          fi

          # 중복된 디렉토리 제거
          modified_dirs=($(printf "%s\n" "${modified_dirs[@]}" | sort -u))

          echo "Modified directories: ${modified_dirs[@]}"
          echo "Number of modified directories: ${#modified_dirs[@]}"  # 수정된 디렉토리 개수 출력

          # 수정된 디렉토리들에 대해 Cloud Function을 배포
          for dir in "${modified_dirs[@]}"; do
            function_name=$(basename "$dir")  # 함수 이름 가져오기
            echo "Deploying function: $function_name from directory: $dir"
            gcloud functions deploy ${function_name} \
              --region us-central1 \
              --runtime nodejs20 \
              --source "$dir" \
              --entry-point ${function_name} \
              --trigger-http \
              --allow-unauthenticated \
              --timeout 60 \
              --max-instances 1 \
              --no-gen2

            echo "Function $function_name deployed successfully."  # 배포 성공 메시지 출력
          done
