name: Deployment

on:
  push:
    branches:
      - main  # main 브랜치에 푸시될 때만 작동

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      # Authenticate to Google Cloud
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      # Set up Google Cloud SDK
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      # Get modified files (src 파일 안에 수정된 파일들만 필터링)
      - name: Get changed files
        id: filter
        uses: dorny/paths-filter@v2
        with:
          list-files: shell
          filters: |
            src:
              - 'src/**/*.js'  # JS 파일만 감지

      # Deploy the Cloud Functions
      - name: Deploy Cloud Functions
        if: ${{ steps.filter.outputs.src == 'true' }}
        run: |
          # 임시 디렉토리 생성
          deploy_dir=$(mktemp -d)

          modified_files=($(echo "${{ steps.filter.outputs.src_files }}" | tr ',' '\n'))

          echo "Modified files: ${modified_files[@]}"

          cp ./develop_config/{*,.*} "$deploy_dir/" 2>/dev/null || true

          for file in "${modified_files[@]}"; do
            if [[ "$file" == *.js ]]; then

              function_name=$(basename "$file" .js)
              echo "Function Name: ${function_name}"

              cp "$file" "$deploy_dir/index.js"
            fi
          done

          echo "Contents of deploy_dir:"
          ls -la "$deploy_dir"