name: Deployment

on: [push]

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          credentials_file_path: ${{ secrets.GCP_SA_KEY }}

      - name: Deploy Cloud Functions
        run: |
          for file in src/*.py; do
            function_name=$(basename "$file" .py)  # 파일 이름에서 확장자 제거
            echo "Deploying function: $function_name"
            gcloud functions deploy ${function_name}_cf \
              --region europe-west1 \
              --runtime python39 \
              --source src/ \
              --entry-point $function_name \
              --trigger-http \
              --allow-unauthenticated
          done
